### ISSUE TITLE
remove hardcoded disqus credentials.

### ISSUE THREAD

**Issue by ghost** [dragonmantank/solarized-sculpin#2]
https://github.com/dragonmantank/solarized-sculpin/blob/master/_layouts/default.html#L83

**Comment by dragonmantank** [comment]
This should be fixed in 59605d339f88d3cbd6f8306facc8fd5e453f86d9 now. You can set a Disqus shortname in `sculpin_site.yml`, just like the blog skeleton:

```
disqus:
  shortname: YOUR_SHORTNAME_HERE
```
